---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappbluedeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: Java-Web-App
      version: v1
      color: blue
  template:
    metadata:
      name: Javawebapppod
      labels:
        app: Java-Web-App
        version: v1 
        color: blue
    spec:
      containers:
      - name: javawebappcontainer
        image: mellitus/javawebapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
...