---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappgreendeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: Java-Web-App
      version: v2
      color: green
  template:
    metadata:
      name: Javawebapppod
      labels:
        app: Java-Web-App
        version: v2 
        color: green
    spec:
      containers:
      - name: javawebappcontainer
        image: mellitus/javawebapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
...