---
apiVersion: v1
kind: Namespace
metadata: 
  name: javadbns
---
apiVersion: v1
kind: Pod
metadata:
  name: javawebpod
  labels:
    app: javawebs
spec:
  containers:
  - name: javawebcontainers
    image: ashokit/javawebapp
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:javawebsvc
spec:
  type: ClusterIP
  selector:
    app:javawebs
  ports:
  - port: 80
    targetPort: 8080
    NodePort: 30456f
...