---
apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
spec:
  replicas: 3
  selector: 
    app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:  
      app: javawebapp
    spec:
      containers:
        name: javawebcontainers
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
- name: name:javawebsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
...