apiVersion: v1
kind: Secret
metadata:
  name: weshopify-db-secret-config
  labels:
    secret: weshopify-db-secret-config
data:
  DB_USER_NAME_VALUE: cm9vdA==
  DB_PASSWORD_VALUE: cm9vdA==
type: Opaque
---
# ======================================
# Reading data from configmap and secret
# ======================================
- name: DB_DRIVER_CLASS
          valueFrom:
            configMapKeyRef:
              name: weshopify-db-config-map
              key: DB_DRIVER_NAME_VALUE

- name: DB_PASSWORD
          valueFrom:
            passowrdKeyRef:
              name: weshopify-db-secret-config
              key: DB_DRIVER_NAME_VALUE
